apiVersion: v1
kind: Service
metadata:
  name: {{ include "fin-predictor.fullname" . }}
  labels:
    {{- include "fin-predictor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
    - 192.168.105.6
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fin-predictor.selectorLabels" . | nindent 4 }}
